### configure CMake to link against Qt4
FIND_PACKAGE( Qt4 REQUIRED )
SET( QT_USE_QTXML TRUE )
INCLUDE(${QT_USE_FILE})

### configure CMake to link against laral libraries
FIND_PACKAGE (LARAL REQUIRED)

IF (NOT NNFW_FOUND)

MESSAGE(STATUS "Using NNFW version @VER_MAJ@.@VER_MIN@.@VER_PAT@")
MESSAGE(STATUS "Apply the Macro TARGET_USE_NNFW(targetname) for use NNFW")

###################################
### MACRO for C++ Project       ##
##################################
MACRO( TARGET_USE_NNFW targetname )

GET_TARGET_PROPERTY( OLD1 ${targetname} COMPILE_FLAGS )
IF ( OLD1 MATCHES NOTFOUND )
	SET( OLD1 "" )
ENDIF( OLD1 MATCHES NOTFOUND )
SET_TARGET_PROPERTIES( ${targetname} PROPERTIES COMPILE_FLAGS "${OLD1} ${LARAL_COMPILE_FLAGS} @INCLUDES_CPP@" )
GET_TARGET_PROPERTY( OLD2 ${targetname} LINK_FLAGS )
IF ( OLD2 MATCHES NOTFOUND )
	SET( OLD2 "" )
ENDIF( OLD2 MATCHES NOTFOUND )
SET_TARGET_PROPERTIES( ${targetname} PROPERTIES LINK_FLAGS "${OLD2} ${LARAL_LINK_FLAGS}" )
TARGET_LINK_LIBRARIES( ${targetname} ${QT_LIBRARIES} ${LARAL_LIBRARIES} )
TARGET_LINK_LIBRARIES( ${targetname} "@LIBRARIES_CPP@" )

ENDMACRO(TARGET_USE_NNFW)

SET (NNFW_FOUND TRUE)
ENDIF (NOT NNFW_FOUND)
