
### Check is the version required is compatible
SET( PACKAGE_VERSION "@VER_MAJ@.@VER_MIN@.@VER_PAT@" )
#SET( PACKAGE_VERSION_EXACT TRUE )
#SET( PACKAGE_VERSION_COMPATIBLE TRUE )

IF ( PACKAGE_FIND_VERSION_MAJOR EQUAL @VER_MAJ@ AND PACKAGE_FIND_VERSION_MINOR EQUAL @VER_MIN@ AND PACKAGE_FIND_VERSION_PATCH EQUAL @VER_PAT@ )
	SET( PACKAGE_VERSION_EXACT TRUE )
ELSE ( PACKAGE_FIND_VERSION_MAJOR EQUAL @VER_MAJ@ AND PACKAGE_FIND_VERSION_MINOR EQUAL @VER_MIN@ AND PACKAGE_FIND_VERSION_PATCH EQUAL @VER_PAT@ )
	SET( PACKAGE_VERSION_EXACT FALSE )
ENDIF ( PACKAGE_FIND_VERSION_MAJOR EQUAL @VER_MAJ@ AND PACKAGE_FIND_VERSION_MINOR EQUAL @VER_MIN@ AND PACKAGE_FIND_VERSION_PATCH EQUAL @VER_PAT@ )

IF ( PACKAGE_FIND_VERSION_MAJOR EQUAL @VER_MAJ@ AND PACKAGE_FIND_VERSION_MINOR LESS @VER_MIN@ )
	SET( PACKAGE_VERSION_COMPATIBLE TRUE )
ELSE ( PACKAGE_FIND_VERSION_MAJOR EQUAL @VER_MAJ@ AND PACKAGE_FIND_VERSION_MINOR LESS @VER_MIN@ )
	SET( PACKAGE_VERSION_COMPATIBLE FALSE )
ENDIF ( PACKAGE_FIND_VERSION_MAJOR EQUAL @VER_MAJ@ AND PACKAGE_FIND_VERSION_MINOR LESS @VER_MIN@ )

IF ( PACKAGE_VERSION_EXACT )
	SET( PACKAGE_VERSION_COMPATIBLE TRUE )
ENDIF ( PACKAGE_VERSION_EXACT )