### configure CMake to link against Qt4
FIND_PACKAGE( Qt4 REQUIRED )
SET( QT_USE_QTXML TRUE )
INCLUDE(${QT_USE_FILE})

IF (NOT NNFW_FOUND)

MESSAGE(STATUS "Using NNFW version @VER_MAJ@.@VER_MIN@.@VER_PAT@")
MESSAGE(STATUS "Apply the Macro TARGET_USE_NNFW(targetname) for use NNFW")

SET( NNFW_CONFIG @NNFW_CONFIG@ )
SET( USE_FRAMEWORKS @USE_FRAMEWORKS@ )

### Check is the version required is compatible
SET( PACKAGE_VERSION "@VER_MAJ@.@VER_MIN@.@VER_PAT@" )
SET( PACKAGE_VERSION_EXACT TRUE )
SET( PACKAGE_VERSION_COMPATIBLE TRUE )
#
#IF ( PACKAGE_FIND_VERSION_MAJOR=="@VER_MAJ@" AND PACKAGE_FIND_VERSION_MINOR=="@VER_MIN@" AND PACKAGE_FIND_VERSION_PATCH=="@VER_PAT@" )
#	SET( PACKAGE_VERSION_EXACT TRUE )
#ELSE ( PACKAGE_FIND_VERSION_MAJOR=="@VER_MAJ@" AND PACKAGE_FIND_VERSION_MINOR=="@VER_MIN@" AND PACKAGE_FIND_VERSION_PATCH=="@VER_PAT@" )
#	SET( PACKAGE_VERSION_EXACT FALSE )
#ENDIF ( PACKAGE_FIND_VERSION_MAJOR=="@VER_MAJ@" AND PACKAGE_FIND_VERSION_MINOR=="@VER_MIN@" AND PACKAGE_FIND_VERSION_PATCH=="@VER_PAT@" )
#IF ( PACKAGE_FIND_VERSION_MAJOR<="@VER_MAJ@" AND PACKAGE_FIND_VERSION_MINOR<="@VER_MIN@" )
#	SET( PACKAGE_VERSION_COMPATIBLE TRUE )
#ELSE ( PACKAGE_FIND_VERSION_MAJOR<="@VER_MAJ@" AND PACKAGE_FIND_VERSION_MINOR<="@VER_MIN@" )
#	SET( PACKAGE_VERSION_COMPATIBLE FALSE )
#ENDIF ( PACKAGE_FIND_VERSION_MAJOR<="@VER_MAJ@" AND PACKAGE_FIND_VERSION_MINOR<="@VER_MIN@" )

###################################
### MACRO for C++ Project       ##
##################################
MACRO( TARGET_USE_NNFW targetname )

GET_TARGET_PROPERTY( OLD1 ${targetname} COMPILE_FLAGS )
IF ( OLD1 MATCHES NOTFOUND )
	SET( OLD1 "" )
ENDIF( OLD1 MATCHES NOTFOUND )
SET_TARGET_PROPERTIES( ${targetname} PROPERTIES COMPILE_FLAGS "${OLD1} @INCLUDES@ @CFLA@ @CPP_FW@" )

GET_TARGET_PROPERTY( OLD2 ${targetname} LINK_FLAGS )
IF ( OLD2 MATCHES NOTFOUND )
	SET( OLD2 "" )
ENDIF( OLD2 MATCHES NOTFOUND )
SET_TARGET_PROPERTIES( ${targetname} PROPERTIES LINK_FLAGS "${OLD2} @LFLA@ @CPPLIB@" )

TARGET_LINK_LIBRARIES( ${targetname} ${QT_LIBRARIES} )
IF( NOT USE_FRAMEWORKS )
	TARGET_LINK_LIBRARIES( ${targetname} "nnfw" )
ENDIF( NOT USE_FRAMEWORKS )

ENDMACRO(TARGET_USE_NNFW)


###################################
### MACRO for C Project         ##
##################################
MACRO( TARGET_USE_CNNFW targetname )

GET_TARGET_PROPERTY( OLD1 ${targetname} COMPILE_FLAGS )
IF ( OLD1 MATCHES NOTFOUND )
	SET( OLD1 "" )
ENDIF( OLD1 MATCHES NOTFOUND )
SET_TARGET_PROPERTIES( ${targetname} PROPERTIES COMPILE_FLAGS "${OLD1} @INCLUDES@ @CFLA@ @C_FW@" )

GET_TARGET_PROPERTY( OLD2 ${targetname} LINK_FLAGS )
IF ( OLD2 MATCHES NOTFOUND )
	SET( OLD2 "" )
ENDIF( OLD2 MATCHES NOTFOUND )
SET_TARGET_PROPERTIES( ${targetname} PROPERTIES LINK_FLAGS "${OLD2} @LFLA@ @CLIB@" )

TARGET_LINK_LIBRARIES( ${targetname} ${QT_LIBRARIES} )
IF( NOT USE_FRAMEWORKS )
	TARGET_LINK_LIBRARIES( ${targetname} "cnnfw" )
ENDIF( NOT USE_FRAMEWORKS )

ENDMACRO(TARGET_USE_CNNFW)

SET (NNFW_FOUND TRUE)
ENDIF (NOT NNFW_FOUND)
